
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rizaalvin
 */
public class Frame3 extends javax.swing.JFrame {

    /**
     * Creates new form Frame3
     */
    public Frame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TFTinggi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFPanjang = new javax.swing.JTextField();
        TFLebar = new javax.swing.JTextField();
        BBalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TFSisi = new javax.swing.JTextField();
        BKubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BBola = new javax.swing.JButton();
        TFJari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 400, 50);

        jPanel1.setLayout(null);

        jLabel2.setText("Tinggi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 110, 60, 20);
        jPanel1.add(TFTinggi);
        TFTinggi.setBounds(130, 110, 160, 30);

        jLabel3.setText("Panjang");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 30, 60, 20);

        jLabel4.setText("Lebar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 70, 60, 20);
        jPanel1.add(TFPanjang);
        TFPanjang.setBounds(130, 30, 160, 30);
        jPanel1.add(TFLebar);
        TFLebar.setBounds(130, 70, 160, 30);

        BBalok.setText("Hitung");
        BBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBalokActionPerformed(evt);
            }
        });
        jPanel1.add(BBalok);
        BBalok.setBounds(140, 170, 80, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel5.setText("Panjang Sisi");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 40, 90, 20);
        jPanel2.add(TFSisi);
        TFSisi.setBounds(120, 70, 160, 30);

        BKubus.setText("Hitung");
        BKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKubusActionPerformed(evt);
            }
        });
        jPanel2.add(BKubus);
        BKubus.setBounds(160, 110, 80, 30);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel6.setText("Jari-Jari");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 50, 70, 20);

        BBola.setText("Hitung");
        BBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBolaActionPerformed(evt);
            }
        });
        jPanel3.add(BBola);
        BBola.setBounds(140, 100, 90, 30);
        jPanel3.add(TFJari);
        TFJari.setBounds(100, 50, 180, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 60, 400, 240);

        setBounds(0, 0, 421, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void BBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBalokActionPerformed
        // Menghitung volume balok:
        int panjang,lebar,tinggi;
        panjang = Integer.parseInt(TFPanjang.getText());
        lebar = Integer.parseInt(TFLebar.getText());
        tinggi = Integer.parseInt(TFTinggi.getText());
        int hasil = panjang * lebar * tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil+" luas","Volume Balok",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BBalokActionPerformed

    private void BKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi=Integer.parseInt(TFSisi.getText());
        int hasil = sisi*sisi*sisi;
        
        try{
            JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus Adalah : "+hasil," luas",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BKubusActionPerformed

    private void BBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari=Integer.parseInt(TFJari.getText());
        float hasil1=(float) (4/3*3.14*jari*jari*jari);
        try{
            JOptionPane.showMessageDialog(null, "Luas Permukaan Bola Adalah : "+hasil1," luas", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBalok;
    private javax.swing.JButton BBola;
    private javax.swing.JButton BKubus;
    private javax.swing.JTextField TFJari;
    private javax.swing.JTextField TFLebar;
    private javax.swing.JTextField TFPanjang;
    private javax.swing.JTextField TFSisi;
    private javax.swing.JTextField TFTinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
